pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                bat 'mvn clean install -DskipTests'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn clean test'
            }
        }

        stage('Deploy') {
            steps {
                bat 'echo Deploying application...'
            }
        }

    }
}
