baseUrl=https://www.99acres.com
propertyUrl=https://www.99acres.com/3-bhk-bedroom-apartment-flat-for-sale-in-aba-cleo-county-sector-121-noida-1620-sq-ft-spid-C89755690
platform=msite
browser=chrome
timeout=20
